# ==========================================
# Basic
# ==========================================
version: v1
run_name: exp1

# ==========================================
# Model
# ==========================================
model: efficientnet # efficientnet / resnet（之後可加）

# ==========================================
# Loss
# ==========================================
loss_name: cross_entropy # cross_entropy / focal_loss（之後可加）
