# ==========================================
# Basic
# ==========================================
version: v1
run_name: exp1

# ==========================================
# Model
# ==========================================
model: efficientnet # efficientnet / resnet（之後可加）

# ==========================================
# Training
# ==========================================
epochs: 10
lr: 0.001
batch_size: 16
num_workers: 4
